# 로컬 개발 환경 구성
spring:
  datasource:
    #    url: jdbc:h2:mem:test
    #    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_URL}:17863/hagima
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    com:
      example:
        hagimabackend:
          DEBUG
#
#oauth2:
#  kakao:
#    infoUrl: https://kapi.kakao.com
#    baseUrl: https://kauth.kakao.com
#    clientId: 3fca0db05482af0333a5fb5b9dc5b345
#    redirectUri: https://bbok.kro.kr/api/v1/account/kakao/result
#    secretKey: ${SECRET_KEY}
#
#cloud:
#  aws:
#    credentials:
#      access-key: ${S3_ACCESS}
#      secret-key: ${S3_SECRET}
#    s3:
#      bucket: ${S3_BUCKET}
#    stack:
#      auto: false
#    region:
#      static: ap-northeast-2